### ISSUE TITLE
pg2k4j not working correctly on PostgreSQL version 11.x

### ISSUE THREAD

**Issue by teej** [disneystreaming/pg2k4j#27]
I have two Postgres databases that I'm trying to use with pg2k4j. The first is on version 9.6.x and works like a charm. The second is on 11.2.x and runs into issues.

1. When I try to connect with SSL, the connection ends up getting dropped right away, giving the error `Database connection failed when writing to copy`. 
2. When I turn SSL off, I get at most one batch of records, and then nothing but empty record sets `{ stream: '...', manual: 0, count: 0, size: 0, matches: 0, timed: 0, UserRecords: 0, KinesisRecords: 0 }`

After running pg2k4j with the Java Postgres driver logging turned all the way up, I saw weird packet errors that indicate https://github.com/pgjdbc/pgjdbc/issues/1466 as the root cause. The fact that folks using Debezium also have issues with number 1 (see https://groups.google.com/forum/#!msg/debezium/ocmQdBL6_Rk/BvKt3Yp3AQAJ) supports that pgjdbc is the problem.

I'd love to know if others are having problems with 11.x and to find out if there is a workaround.

**Comment by rkass** [comment]
Hi @teej thanks for submitting. We have used pg2k4j with postgres 10 databases so it's interesting to hear about your experiences with version 11. Since we're not yet using pg 11 we haven't had the opportunity to observe the issue you describe.

I did create this pr https://github.com/disneystreaming/pg2k4j/pull/28/files which introduces integration tests with version 11 of postgres. For now the tests passed as is (same recipe for db version 10 and 11), but if you could add tests that break with db version 11 and not db version 10 that'd go a long way to discovering if there is a problem and hunting down a fix.

**Comment by teej** [comment]
@rkass Thanks for taking a look! I’ll take a crack at trying to repro the issue with test cases.

**Comment by Tybot204** [comment]
For what it's worth, I have pg2k4j working with pg 11.5. It's possible < pg 11.5 had an issue that has since been resolved? Either that or some config is causing the issue in particular.

I setup pg2k4j following the README verbatim with the following setup:
* PG 11.5 running in AWS RDS (no public accessibility)
* EKS running in the same VPC
* pg2k4j running as a stand alone deployment in Kubernetes
  * Options set include `awsaccesskey`, `awssecret`, `pgdatabase`, `pghost`, `pgpassword`, `pguser`, `region`, and `streamname`
